from __future__ import annotations

from .analysis_core import (
    analyze_spatiotemporal_frequency,
    build_angle_profile,
    render_summary_figure,
    resolve_output_dir,
    resolve_video_path,
)
from .app import build_arg_parser, main, run_analysis
from .constants import (
    DEFAULT_ANGULAR_RESOLUTION,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_ROI_FRAME_STRATEGY,
    DEFAULT_ROI_REFERENCE_MAX_FRAMES,
    DEFAULT_ROI_SCORE_THRESHOLD,
    DEFAULT_VIDEO_DIR,
)
from .models import (
    AnalysisResult,
    ROICandidate,
    ROICandidateScore,
    ROIConfig,
    ROIReferenceContext,
    ROIReferenceFrames,
    ROISelectionResult,
)
from .outputs import draw_candidate_on_frame, save_analysis_outputs, save_roi_debug_outputs
from .roi_detection import (
    build_provided_selection_result,
    build_reference_context,
    candidate_from_roi_config,
    candidate_record,
    clip_candidate_radius,
    deduplicate_candidates,
    estimate_radius_from_support,
    generate_candidates_from_detector,
    generate_candidates_from_manual,
    generate_candidates_from_motion,
    generate_candidates_from_static_structure,
    load_roi_config,
    merge_manual_fallback,
    resolve_roi_candidate,
    roi_config_from_candidate,
    sample_reference_frames,
    save_roi_config,
    score_roi_candidate,
    select_best_roi_candidate,
    select_roi,
    select_roi_interactively,
)
from .support import compute_edge_map, downscale_gray, jsonable, normalize_map, read_frames_at_indices, save_json

__all__ = [
    "DEFAULT_VIDEO_DIR",
    "DEFAULT_OUTPUT_DIR",
    "DEFAULT_ANGULAR_RESOLUTION",
    "DEFAULT_ROI_FRAME_STRATEGY",
    "DEFAULT_ROI_REFERENCE_MAX_FRAMES",
    "DEFAULT_ROI_SCORE_THRESHOLD",
    "ROIConfig",
    "ROICandidate",
    "ROICandidateScore",
    "ROIReferenceFrames",
    "ROIReferenceContext",
    "ROISelectionResult",
    "AnalysisResult",
    "normalize_map",
    "jsonable",
    "save_json",
    "compute_edge_map",
    "downscale_gray",
    "read_frames_at_indices",
    "sample_reference_frames",
    "build_reference_context",
    "select_roi",
    "build_angle_profile",
    "analyze_spatiotemporal_frequency",
    "resolve_video_path",
    "resolve_output_dir",
    "load_roi_config",
    "save_roi_config",
    "candidate_from_roi_config",
    "roi_config_from_candidate",
    "select_roi_interactively",
    "generate_candidates_from_manual",
    "generate_candidates_from_detector",
    "clip_candidate_radius",
    "deduplicate_candidates",
    "estimate_radius_from_support",
    "generate_candidates_from_motion",
    "generate_candidates_from_static_structure",
    "score_roi_candidate",
    "candidate_record",
    "build_provided_selection_result",
    "select_best_roi_candidate",
    "merge_manual_fallback",
    "resolve_roi_candidate",
    "render_summary_figure",
    "draw_candidate_on_frame",
    "save_roi_debug_outputs",
    "save_analysis_outputs",
    "run_analysis",
    "build_arg_parser",
    "main",
]
